from . import admission_application
from . import merit_list
from . import entry_test
from . import pre_test_config
from . import custom_log
from . import fee_barcode
from . import admission_register
from . import admission_doc
from . import odoocms_program
from . import models_inherit
from . import study_scheme
from . import fee_payment_reg_no
from . import email_sms_custom
from . import prospectus_fee_waiver_type