{
    "name": "OdooCMS Registration",
    "version": "14.0",
    "license": "LGPL-3",
    "category": "OdooCMS",
    "sequence": 3,
    "summary": "Registration Management Module of OdooCMS",
    "author": "AARSOL",
    "company": "AARSOL",
    "website": "http://www.aarsol.com/",
    "depends": ["odoocms"],
    "data": [
        "security/odoocms_registration_security.xml",
        "security/ir.model.access.csv",
        "data/registration_data.xml",
        "data/sequence.xml",
        "menu/registration_menu_view.xml",
        "views/batch_section_view.xml",
        "views/term_scheme_view.xml",
        "views/class_view.xml",
        "views/course_registration_view.xml",
        "views/course_registration_bulk_view.xml",
        "views/course_registration_bulk2_view.xml",
        "views/student_registration_view.xml",
        "views/student_view.xml",
        "views/student_registration_load_view.xml",
        "views/program_view.xml",
        "views/inherits_view.xml",
        "views/faculty_staff_view.xml",
        "views/faculty_staff_load.xml",
        "views/class_generator_view.xml",
        "views/change_course_info_view.xml",
        "views/res_config_setting_view.xml",
        "views/student_courses_shift_view.xml",
        "views/course_shift_view.xml",
        "views/course_drop_view.xml",
        "views/course_withdraw_reinstate_view.xml",
        "views/requests/student_request_term_view.xml",
        "views/requests/student_request_fee_view.xml",
        "views/requests/student_request_view.xml",
        "views/requests/student_request.xml",

        'wizard/registration_cache_wiz.xml',
        "wizard/auto_enrollment.xml",
        "wizard/teacher_course_load.xml",
        "wizard/teacher_info_report.xml",
        "wizard/withdraw_reinstate_report.xml",
        "wizard/student_convocation_list.xml",
        "wizard/cancel_registration_request.xml",
        # 'wizard/register_scheme_course_view.xml',
        "wizard/assign_section_wiz_view.xml",
        # 'wizard/assign_teacher_wiz_view.xml',
        # 'wizard/assign_domain_rule_wiz_view.xml',
        # 'wizard/promote_students.xml',
        # 'wizard/merge_section.xml',

        "reports/unofficial_transcript.xml",
        "reports/registration_stat_report.xml",
        "reports/teacher_course_load.xml",
        "reports/teacher_info_report.xml",
        "reports/withdraw_reinstate_report.xml",
        "reports/student_convocation_list_report.xml",
        "reports/registration_stat_detail_report.xml",
        "reports/report.xml",
    ],
    "images": ["static/description/banner.jpg"],
    "installable": True,
    "auto_install": False,
    "application": True,
}
