{
    'name': 'Need-Based Scholarship',
    'version': '1.0.0',
    'summary': 'CMU Need-Based Scholarship application (portal + backend)',
    'description': 'Need-based scholarship module cloned from DF flow, with validations and menus.',
    'category': 'Admission',
    'author': 'MIS',
    'website': '',
    'license': 'LGPL-3',
    'depends': [
        'odoocms_base',
        'mail',
        'odoocms',
        'odoocms_admission_cust_ext_a',
        #"odoocms_admission_mis",
        'odoocms_admission',
        'odoocms_assets',
        'odoocms_admission_fee',
        'odoocms_merit_ucp',
        'website',
    ],
    'data': [
        'views/nbs_portal.xml',
        'views/nbs_backend.xml',
        'views/nbs_pdf_report.xml',
        'views/nbs_pdf_action.xml',
        # 'views/nbs_portal_template1.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
