{
    "name": "OdooCMS Fee",
    'version': '13.0',
    'license': 'LGPL-3',
    'category': 'OdooCMS',
    'sequence': 3,
    'summary': "Fee Management Module of OdooCMS""",
    'author': 'AARSOL',
    'company': 'AARSOL',
    'website': "http://www.aarsol.com/",
    "depends": ['account', 'analytic','odoocms_registration', 'aarsol_payment_term_ext', 'account_invoice_fixed_discount'],
    "data": [
        'data/refund_data.xml',
        'data/sequence.xml',
        'security/odoocms_fee_security.xml',
        'security/ir.model.access.csv',
        'menu/odoocms_fee_menu_view.xml',

        'wizard/import_wiz/fee_payment_register_import_wizard_view.xml',
        'wizard/import_wiz/cpr_student_list_import_wizard_view.xml',

        # Views
        'views/odoocms_fee_category.xml',
        'views/odoocms_fee_payment_terms.xml',
        'views/odoocms_fee_structure.xml',
        'views/odoocms_registration.xml',

        'views/account_move_inherit_view.xml',
        'views/account_move_group_view.xml',
        'views/odoocms_fee_receipt.xml',
        'views/odoocms_fee_challan.xml',
        'views/odoocms_fee_waiver.xml',
        'views/odoocms_fee_student_ledger_view.xml',
        'views/odoocms_fee_journal_dashboard_view.xml',
        'views/odoocms_fee_journal_inherit.xml',
        'views/cms_core_inherit.xml',
        'views/student_view.xml',
        'views/odoocms_fee_refund_type.xml',

        'views/adjustment_request_view.xml',
        'views/odoocms_fee_res_config_setting_view.xml',
        'views/odoocms_fee_payment_register_view.xml',

        'views/odoocms_fee_receipt_deletion_log_view.xml',
        'views/odoocms_fee_student_ledger_changes_log_view.xml',
        'views/odoocms_fee_student_ledger_deletion_log_view.xml',
        'views/odoocms_fee_payment_deletion_log_view.xml',

        'views/odoocms_tuition_fee_deferment_view.xml',
        'views/odoocms_late_fee_knockoff_view.xml',
        'views/odoocms_fee_refund_request_view.xml',
        'views/odoocms_fee_advance_payment_view.xml',
        'views/account_move_line_views.xml',
        'views/odoocms_student_scholarship_view.xml',
        'views/odoocms_receipts_fee_head_removal_view.xml',
        'views/odoocms_student_suspension_view.xml',
        'views/odoocms_student_cpr_view.xml',
        'views/odoocms_student_fee_previous_balance_view.xml',
        'views/odoocms_unconfirmed_paid_bank_challan_view.xml',

        # Wizards/report_wiz
        'wizard/report_wiz/program_wise_fin_summary_wiz_view.xml',
        'wizard/report_wiz/student_fin_report_summary_wiz_view.xml',
        'wizard/report_wiz/receipt_received_summary_wiz_view.xml',
        'wizard/report_wiz/receipt_received_detail_wiz_view.xml',
        'wizard/report_wiz/student_dues_warning_letter_wiz_view.xml',
        'wizard/report_wiz/student_tax_certificate_report_wiz.xml',
        'wizard/report_wiz/head_wise_fee_received_summary_rep_wiz_view.xml',
        'wizard/report_wiz/head_wise_fee_charged_summary_rep_wiz_view.xml',
        'wizard/report_wiz/monthly_head_wise_fee_charged_summary_rep_wiz_view.xml',

        'wizard/report_wiz/dynamic_head_wise_fee_received_summary_rep_wiz_view.xml',
        'wizard/report_wiz/student_fee_charged_rep_wiz_view.xml',


        # Wizard/import_wiz
        'wizard/import_wiz/fee_import_view.xml',

        # Wizard/config_wiz
        'wizard/config_wiz/fee_payment_wiz.xml',
        'wizard/config_wiz/fee_receipt_validate_wiz_view.xml',
        'wizard/config_wiz/fee_reversal_process_view.xml',
        'wizard/config_wiz/generate_invoice_view.xml',
        # 'wizard/config_wiz/generate_invoice_recheking.xml',
        'wizard/config_wiz/process_fee_payment_view.xml',
        'wizard/config_wiz/split_invoice_view.xml',
        'wizard/config_wiz/fee_receipt_cancel_wiz_view.xml',
        'wizard/config_wiz/receipt_reversal_view.xml',
        'wizard/config_wiz/payment_change_paid_date_view.xml',
        'wizard/config_wiz/fee_receipt_recompute_total_amount_view.xml',
        'wizard/config_wiz/fee_receipt_barcode_assign_view.xml',
        'wizard/config_wiz/odoocms_student_fee_ledger_update_view.xml',
        'wizard/config_wiz/challan_rollback_wiz_view.xml',
        'wizard/config_wiz/challan_merge_wiz_view.xml',
        'wizard/config_wiz/payment_bank_change_wiz_view.xml',

        # Reports
        'report/report_invoice.xml',
        'report/program_wise_fin_summary_report.xml',
        'report/student_dues_warning_letter_report.xml',
        'report/receipt_received_summary_report.xml',
        'report/receipt_received_detail_report.xml',
        'report/student_fin_report_summary_report.xml',
        'report/student_invoice_landscape.xml',
        'report/fee_payment_register_report.xml',
        'report/fee_receivable_report.xml',
        'report/fee_generation_status_report.xml',
        'report/fee_tax_report.xml',
        'report/scholarship_awardees_report.xml',
        'report/student_tags_summary_report.xml',
        'report/student_tags_detail_report.xml',
        'report/student_tax_certificate_report.xml',
        'report/head_wise_fee_received_summary_report.xml',
        'report/head_wise_fee_charged_summary_report.xml',
        'report/monthly_head_wise_fee_charged_summary_report.xml',
        'report/student_ledger_report.xml',

        # Scholarship
        'report/scholarship_charged_report.xml',
        'report/scholarship_received_report.xml',
        'report/report.xml',
    ],
    "installable": True,
    "auto_install": False,
    'application': True,
}
